### ISSUE TITLE
Technical Character Set & Box Drawing

### ISSUE THREAD

**Issue by hackerb9** [phoikoi/VT323#7]
The font appears to be missing the DEC [Technical Character Set](https://vt100.net/charsets/technical.html) which was used for writing mathematical equations in character cell terminals like the VT320. 

It also does not seem to have the "DEC Special Graphics" characters (also known as "VT100 Box Drawing").

Both of these character sets were builtin to the VT320.

**Comment by phoikoi** [comment]
Thanks for creating an issue.  You'll note that this font is a Unicode font which emulates/mimics the characteristics of the VT320 Latin-1 character set, rather than an exact copy of the original DEC bitmap font.  It's not meant to be a functional replacement for the original, but an aesthetic homage to it.  Consequently, the special character blocks in the DEC character encoding are not included.  Unicode has its own box drawing and mathematical glyphs, which many times will be substituted from a fallback font by a terminal emulator if they're not included in the primary font selected.  Unfortunately, I am not aware of a direct replacement for the VT320 original, with all of the exact encodings and extra glyphs.  Sorry about that.

**Comment by hackerb9** [comment]
Thank you. I didn't mean to suggest the missing characters would use the pre-unicode encodings. Just that, instead of having the terminal emulator substitute some other font, it would look more aesthetically pleasing if VT323 contained more of the characters the VT320 was actually capable of.  Terminal emulators such as xterm automatically handle converting DEC's special character blocks (ISO 2022) into Unicode. Here's an example from vttest:

![Example of character sets from vttest](https://user-images.githubusercontent.com/10174223/210163461-4ed8db5c-6ba8-4cc7-9d20-00a3881741bb.png)

If you look at the box drawing and technical characters, you'll notice that they don't match the rest of the VT323 font.
